### ISSUE TITLE
add exchange crypto "Buy and sell leading cryptocurrencies"

### ISSUE THREAD

**Issue by cubanitoalex** [cuban-opensourcers/cuban-restricted#25]
binance,bybit,BitMEX,ftx,okex,kraken,poloniex,bitfinex,deribit,bitstamp,coinbase,bitso,gemini,Crypto

**Comment by HugoFlorentino** [comment]
Now that Cuba has recognized and regulated use of cryptocurrencies for payments, this should probably be considered.
