### ISSUE TITLE
additional GEO-blocked services

### ISSUE THREAD

**Issue by ofarrill** [cuban-opensourcers/cuban-restricted#54]
uphold.com
developer.apple.com
avid.com
ifconfig.me
ipinfo.io
ko-fi.com
rippling.com
intuit.com

**Comment by cccaballero** [comment]
Added

**Comment by abdullahdevrel** [comment]
I am the DevRel of IPinfo. Our services are blocked in Cuba because we use GCP. 

https://support.google.com/cloudidentity/answer/2891389?hl=en

> Google restricts access to some of its business services in certain countries or regions, such as Crimea, Cuba, the so-called Donetsk People's Republic and Luhansk People's Republic, Iran, North Korea, and Syria

**Comment by ofarrill** [comment]
remitly.com - is not GEO blocked but payments will fail when initiated from Cuba.
